// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAUxjZy7SQ071Wa4Ppg1s8KOpFUOxe93xI',
    appId: '1:170248424793:web:380bf3e0d73298bb321048',
    messagingSenderId: '170248424793',
    projectId: 'stockwise-kri',
    authDomain: 'stockwise-kri.firebaseapp.com',
    storageBucket: 'stockwise-kri.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCv3KWOBkSzGYIyqK_uCxGYEMNj5E8Fh4w',
    appId: '1:170248424793:android:db83211b067da955321048',
    messagingSenderId: '170248424793',
    projectId: 'stockwise-kri',
    storageBucket: 'stockwise-kri.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBtnS1mCDpCYaL4vDfme0RwkW6qnxVwF1M',
    appId: '1:170248424793:ios:fcacf5629073713b321048',
    messagingSenderId: '170248424793',
    projectId: 'stockwise-kri',
    storageBucket: 'stockwise-kri.firebasestorage.app',
    iosBundleId: 'com.example.stockWise',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBtnS1mCDpCYaL4vDfme0RwkW6qnxVwF1M',
    appId: '1:170248424793:ios:fcacf5629073713b321048',
    messagingSenderId: '170248424793',
    projectId: 'stockwise-kri',
    storageBucket: 'stockwise-kri.firebasestorage.app',
    iosBundleId: 'com.example.stockWise',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAUxjZy7SQ071Wa4Ppg1s8KOpFUOxe93xI',
    appId: '1:170248424793:web:2428c9ac76e0c563321048',
    messagingSenderId: '170248424793',
    projectId: 'stockwise-kri',
    authDomain: 'stockwise-kri.firebaseapp.com',
    storageBucket: 'stockwise-kri.firebasestorage.app',
  );
}
